In [ ]:
import pandas as pd
df = pd.read_csv("Rainfall.csv")
df

,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,rainfall,sunshine,winddirection,windspeed
0,1,1025.9,19.9,18.3,16.8,13.1,72,49,yes,9.3,80.0,26.3
1,2,1022.0,21.7,18.9,17.2,15.6,81,83,yes,0.6,50.0,15.3
2,3,1019.7,20.3,19.3,18.0,18.4,95,91,yes,0.0,40.0,14.2
3,4,1018.9,22.3,20.6,19.1,18.8,90,88,yes,1.0,50.0,16.9
4,5,1015.9,21.3,20.7,20.2,19.9,95,81,yes,0.0,40.0,13.7
...,...,...,...,...,...,...,...,...,...,...,...,...
361,27,1022.7,18.8,17.7,16.9,15.0,84,90,yes,0.0,30.0,18.4
362,28,1026.6,18.6,17.3,16.3,12.8,75,85,yes,1.0,20.0,25.9
363,29,1025.9,18.9,17.7,16.4,13.3,75,78,yes,4.6,70.0,33.4
364,30,1025.3,19.2,17.3,15.2,13.3,78,86,yes,1.2,20.0,20.9
365,31,1026.4,20.5,17.8,15.5,13.0,74,66,no,5.7,20.0,23.3

In [ ]:
df.head()

,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,rainfall,sunshine,winddirection,windspeed
0,1,1025.9,19.9,18.3,16.8,13.1,72,49,yes,9.3,80.0,26.3
1,2,1022.0,21.7,18.9,17.2,15.6,81,83,yes,0.6,50.0,15.3
2,3,1019.7,20.3,19.3,18.0,18.4,95,91,yes,0.0,40.0,14.2
3,4,1018.9,22.3,20.6,19.1,18.8,90,88,yes,1.0,50.0,16.9
4,5,1015.9,21.3,20.7,20.2,19.9,95,81,yes,0.0,40.0,13.7

In [ ]:
df.tail()

,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,rainfall,sunshine,winddirection,windspeed
361,27,1022.7,18.8,17.7,16.9,15.0,84,90,yes,0.0,30.0,18.4
362,28,1026.6,18.6,17.3,16.3,12.8,75,85,yes,1.0,20.0,25.9
363,29,1025.9,18.9,17.7,16.4,13.3,75,78,yes,4.6,70.0,33.4
364,30,1025.3,19.2,17.3,15.2,13.3,78,86,yes,1.2,20.0,20.9
365,31,1026.4,20.5,17.8,15.5,13.0,74,66,no,5.7,20.0,23.3

In [ ]:
#Total Number of Values
df.size

4392

In [ ]:
#rows and columns
df.shape

(366, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   day                     366 non-null    int64
 1   pressure                366 non-null    float64
 2   maxtemp                 366 non-null    float64
 3   temparature             366 non-null    float64
 4   mintemp                 366 non-null    float64
 5   dewpoint                366 non-null    float64
 6   humidity                366 non-null    int64
 7   cloud                   366 non-null    int64
 8   rainfall                366 non-null    object
 9   sunshine                366 non-null    float64
 10           winddirection  365 non-null    float64
 11  windspeed               365 non-null    float64
dtypes: float64(8), int64(3), object(1)
memory usage: 34.4+ KB

In [ ]:
#Checking column names
df.columns

Index(['day', 'pressure ', 'maxtemp', 'temparature', 'mintemp', 'dewpoint',
       'humidity ', 'cloud ', 'rainfall', 'sunshine', '         winddirection',
       'windspeed'],
      dtype='object')

In [ ]:
#Cleaning
df.columns = df.columns.str.strip()

In [ ]:
df.columns

Index(['day', 'pressure', 'maxtemp', 'temparature', 'mintemp', 'dewpoint',
       'humidity', 'cloud', 'rainfall', 'sunshine', 'winddirection',
       'windspeed'],
      dtype='object')

In [ ]:
#checking missing values
df.isna().sum()

day              0
pressure         0
maxtemp          0
temparature      0
mintemp          0
dewpoint         0
humidity         0
cloud            0
rainfall         0
sunshine         0
winddirection    1
windspeed        1
dtype: int64

In [ ]:
#Missing value in windspeed
df[df['windspeed'].isna()]

,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,rainfall,sunshine,winddirection,windspeed
160,9,1005.7,31.7,28.2,26.6,25.7,86,79,yes,6.5,NaN,NaN

In [ ]:
#Missing value in winddirection
df[df['winddirection'].isna()]

,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,rainfall,sunshine,winddirection,windspeed
160,9,1005.7,31.7,28.2,26.6,25.7,86,79,yes,6.5,NaN,NaN

In [ ]:
df['windspeed'] = df['windspeed'].fillna(df['windspeed']).mean()
df['windspeed']

0      21.536986
1      21.536986
2      21.536986
3      21.536986
4      21.536986
         ...
361    21.536986
362    21.536986
363    21.536986
364    21.536986
365    21.536986
Name: windspeed, Length: 366, dtype: float64

In [ ]:
df.loc[160]

day                      9
pressure            1005.7
maxtemp               31.7
temparature           28.2
mintemp               26.6
dewpoint              25.7
humidity                86
cloud                   79
rainfall               yes
sunshine               6.5
winddirection          NaN
windspeed        21.536986
Name: 160, dtype: object

In [ ]:
df[df['winddirection'].isna()]

,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,rainfall,sunshine,winddirection,windspeed
160,9,1005.7,31.7,28.2,26.6,25.7,86,79,yes,6.5,NaN,21.536986

In [ ]:
df.loc[155:165,['day','winddirection','windspeed']]

     day  winddirection  windspeed
155    4          220.0  21.536986
156    5           20.0  21.536986
157    6           20.0  21.536986
158    7           20.0  21.536986
159    8          190.0  21.536986
160    9            NaN  21.536986
161   10          220.0  21.536986
162   11          230.0  21.536986
163   12          220.0  21.536986
164   13          220.0  21.536986
165   14          220.0  21.536986

In [ ]:
df.loc[160,'winddirection'] = 220

In [ ]:
df.loc[160]

day                      9
pressure            1005.7
maxtemp               31.7
temparature           28.2
mintemp               26.6
dewpoint              25.7
humidity                86
cloud                   79
rainfall               yes
sunshine               6.5
winddirection        220.0
windspeed        21.536986
Name: 160, dtype: object

In [ ]:
df.isna().sum()

day              0
pressure         0
maxtemp          0
temparature      0
mintemp          0
dewpoint         0
humidity         0
cloud            0
rainfall         0
sunshine         0
winddirection    0
windspeed        0
dtype: int64

In [ ]:
#Checking duplicate rows
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,windspeed
count,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,3.660000e+02
mean,15.756831,1013.742623,26.191257,23.747268,21.894536,19.989071,80.177596,71.128415,4.419399,101.830601,2.153699e+01
std,8.823592,6.414776,5.978343,5.632813,5.594153,5.997021,10.062470,21.798012,3.934398,81.846390,1.494182e-13
min,1.000000,998.500000,7.100000,4.900000,3.100000,-0.400000,36.000000,0.000000,0.000000,10.000000,2.153699e+01
25%,8.000000,1008.500000,21.200000,18.825000,17.125000,16.125000,75.000000,58.000000,0.500000,40.000000,2.153699e+01
50%,16.000000,1013.000000,27.750000,25.450000,23.700000,21.950000,80.500000,80.000000,3.500000,70.000000,2.153699e+01
75%,23.000000,1018.100000,31.200000,28.600000,26.575000,25.000000,87.000000,88.000000,8.200000,190.000000,2.153699e+01
max,31.000000,1034.600000,36.300000,32.400000,30.000000,26.700000,98.000000,100.000000,12.100000,350.000000,2.153699e+01

In [ ]:
df['windspeed'].value_counts()

windspeed
21.536986    366
Name: count, dtype: int64

In [ ]:
import pandas as pd

df = pd.read_csv("Rainfall.csv")

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
df["windspeed"].isna().sum()

np.int64(1)

In [ ]:
df["windspeed"].value_counts()

windspeed
14.5    6
20.5    5
15.3    4
25.0    4
17.2    4
       ..
15.0    1
9.4     1
27.6    1
18.4    1
33.4    1
Name: count, Length: 223, dtype: int64

In [ ]:
df['windspeed'].mean()

np.float64(21.53698630136986)

In [ ]:
df['windspeed'] = df['windspeed'].fillna(df['windspeed'].mean())

In [ ]:
df['windspeed'].isna().sum()

np.int64(0)

In [ ]:
df.loc[160]

day                      9
pressure            1005.7
maxtemp               31.7
temparature           28.2
mintemp               26.6
dewpoint              25.7
humidity                86
cloud                   79
rainfall               yes
sunshine               6.5
winddirection          NaN
windspeed        21.536986
Name: 160, dtype: object

In [ ]:
df['windspeed'].value_counts()

windspeed
14.5    6
20.5    5
24.4    4
15.3    4
9.2     4
       ..
15.0    1
9.4     1
27.6    1
18.4    1
33.4    1
Name: count, Length: 224, dtype: int64

In [ ]:
df.loc[160,'winddirection'] = 220

In [ ]:
df.loc[160]

day                      9
pressure            1005.7
maxtemp               31.7
temparature           28.2
mintemp               26.6
dewpoint              25.7
humidity                86
cloud                   79
rainfall               yes
sunshine               6.5
winddirection        220.0
windspeed        21.536986
Name: 160, dtype: object

In [ ]:
df.isna().sum()

day              0
pressure         0
maxtemp          0
temparature      0
mintemp          0
dewpoint         0
humidity         0
cloud            0
rainfall         0
sunshine         0
winddirection    0
windspeed        0
dtype: int64

In [ ]:
df['rainfall'].value_counts()

rainfall
yes    249
no     117
Name: count, dtype: int64

In [ ]:
df['rainfall'].value_counts(normalize=True)*100

rainfall
yes    68.032787
no     31.967213
Name: proportion, dtype: float64

In [ ]:
df.groupby('rainfall')['temparature'].mean()

rainfall
no     24.053846
yes    23.603213
Name: temparature, dtype: float64

In [ ]:
df.groupby('rainfall')['humidity'].mean()

rainfall
no     73.000000
yes    83.550201
Name: humidity, dtype: float64

In [ ]:
df.groupby('rainfall')['cloud'].mean()

rainfall
no     51.256410
yes    80.465863
Name: cloud, dtype: float64

In [ ]:
df.groupby('rainfall')['sunshine'].mean()

rainfall
no     7.586325
yes    2.931325
Name: sunshine, dtype: float64

In [ ]:
df.groupby("rainfall")['windspeed'].mean()

rainfall
no     19.275214
yes    22.599747
Name: windspeed, dtype: float64

In [ ]:
df.groupby('rainfall')['pressure'].mean()

rainfall
no     1014.576923
yes    1013.350602
Name: pressure, dtype: float64

In [ ]:
#Finding the maximum and minimum temperature
max = df['maxtemp'].max()
print(max)
min = df['maxtemp'].min()
print(min)

36.3
7.1

In [ ]:
#finding when these temperatures occurred
df.loc[df['maxtemp'].idxmax()]

day                  8
pressure         998.5
maxtemp           36.3
temparature       32.4
mintemp           30.0
dewpoint          24.0
humidity            62
cloud               55
rainfall            no
sunshine          10.8
winddirection    290.0
windspeed         17.2
Name: 220, dtype: object

In [ ]:
df.loc[df['maxtemp'].idxmin()]

day                  24
pressure         1034.6
maxtemp             7.1
temparature         4.9
mintemp             3.1
dewpoint            2.2
humidity             61
cloud                96
rainfall            yes
sunshine            0.0
winddirection      20.0
windspeed          59.5
Name: 23, dtype: object

In [ ]:
#finding 10 hottest days
hottest_10 = df.sort_values('maxtemp', ascending=False).head(10)
hottest_10

,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,rainfall,sunshine,winddirection,windspeed
220,8,998.5,36.3,32.4,30.0,24.0,62,55,no,10.8,290.0,17.2
190,9,999.0,35.6,31.5,26.4,26.4,75,57,yes,10.0,280.0,25.0
176,25,1008.9,35.5,31.4,28.9,26.1,74,39,no,10.6,150.0,9.1
175,24,1008.1,35.2,31.0,28.8,25.0,72,38,no,11.2,180.0,9.0
177,26,1009.1,35.1,31.3,29.4,26.3,75,57,yes,9.9,160.0,11.9
178,27,1007.5,35.1,31.1,28.6,26.7,78,61,yes,8.6,60.0,15.7
206,25,1008.6,35.0,30.8,28.3,25.5,74,28,no,11.0,130.0,8.3
221,9,998.5,34.7,31.0,26.9,24.8,71,80,yes,10.0,220.0,26.4
237,25,1005.5,34.4,30.6,27.9,23.2,65,22,no,9.1,10.0,10.7
171,20,1008.5,34.4,30.8,28.6,26.3,78,59,yes,9.1,170.0,12.1

In [ ]:
#calculating how many of the 10 hottest days were rainy.
hottest_10['rainfall'].value_counts()

rainfall
no     5
yes    5
Name: count, dtype: int64

In [ ]:
##Calculating the percentage of 10 hottest days were rainy
hottest_10['rainfall'].value_counts(normalize=True)*100

rainfall
no     50.0
yes    50.0
Name: proportion, dtype: float64

In [ ]:
#finding 10 coldest days
coldest_10 = df.sort_values("maxtemp",ascending=True).head(10)
coldest_10

,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,rainfall,sunshine,winddirection,windspeed
23,24,1034.6,7.1,4.9,3.1,2.2,61,96,yes,0.0,20.0,59.5
22,23,1027.1,10.4,8.5,7.0,3.4,70,95,yes,0.0,20.0,55.5
24,25,1032.6,10.8,7.4,4.3,3.7,46,25,no,10.1,20.0,28.7
32,2,1024.4,11.2,10.4,9.4,6.8,79,94,yes,0.0,10.0,27.3
25,26,1027.1,13.5,10.4,8.1,2.5,59,85,yes,0.4,20.0,21.3
70,11,1022.6,14.3,11.9,10.0,8.0,77,93,yes,0.0,20.0,25.0
33,3,1023.6,14.3,12.5,10.3,8.6,77,88,yes,0.3,40.0,21.3
47,17,1024.1,14.4,12.9,11.6,8.9,77,91,yes,0.0,20.0,19.2
71,12,1017.7,14.5,13.6,12.7,11.4,87,100,yes,0.0,50.0,36.0
48,18,1021.9,15.0,13.7,11.7,11.8,89,95,yes,0.0,40.0,18.6

In [ ]:
#calculating how many of the 10 coldest days were rainy.
coldest_10['rainfall'].value_counts()

rainfall
yes    9
no     1
Name: count, dtype: int64

In [ ]:
#Calculating the percentage of 10 coldest days were rainy
coldest_10['rainfall'].value_counts(normalize=True)*100

rainfall
yes    90.0
no     10.0
Name: proportion, dtype: float64

In [ ]:
df.groupby("rainfall")['maxtemp'].mean()

rainfall
no     27.070940
yes    25.777912
Name: maxtemp, dtype: float64

In [ ]:
#Correlation analysis
df.corr(numeric_only=True)

,day,pressure,maxtemp,temparature,mintemp,dewpoint,humidity,cloud,sunshine,winddirection,windspeed
day,1.000000,0.044638,-0.017045,-0.014100,-0.009241,-0.051521,-0.118652,-0.113152,0.108927,0.039010,-0.031880
pressure,0.044638,1.000000,-0.829088,-0.851780,-0.839851,-0.860232,-0.274907,0.005621,-0.198171,-0.664231,0.373238
maxtemp,-0.017045,-0.829088,1.000000,0.986193,0.961534,0.899829,0.021882,-0.289765,0.507416,0.630672,-0.441841
temparature,-0.014100,-0.851780,0.986193,1.000000,0.990187,0.936866,0.092030,-0.205895,0.420545,0.649584,-0.393401
mintemp,-0.009241,-0.839851,0.961534,0.990187,1.000000,0.944515,0.139040,-0.156097,0.368288,0.634419,-0.358780
dewpoint,-0.051521,-0.860232,0.899829,0.936866,0.944515,1.000000,0.425282,0.044635,0.185234,0.629386,-0.377963
humidity,-0.118652,-0.274907,0.021882,0.092030,0.139040,0.425282,1.000000,0.655493,-0.563579,0.103195,-0.076578
cloud,-0.113152,0.005621,-0.289765,-0.205895,-0.156097,0.044635,0.655493,1.000000,-0.848334,-0.074503,0.258354
sunshine,0.108927,-0.198171,0.507416,0.420545,0.368288,0.185234,-0.563579,-0.848334,1.000000,0.254535,-0.298777
winddirection,0.039010,-0.664231,0.630672,0.649584,0.634419,0.629386,0.103195,-0.074503,0.254535,1.000000,-0.219332
windspeed,-0.031880,0.373238,-0.441841,-0.393401,-0.358780,-0.377963,-0.076578,0.258354,-0.298777,-0.219332,1.000000

In [ ]:
#Finding the weather conditions most associated with rain
df.groupby("rainfall")[["maxtemp","temparature","mintemp","humidity","cloud","sunshine","pressure","windspeed"]].mean()

,maxtemp,temparature,mintemp,humidity,cloud,sunshine,pressure,windspeed
rainfall,,,,,,,,
no,27.070940,24.053846,21.957265,73.000000,51.256410,7.586325,1014.576923,19.275214
yes,25.777912,23.603213,21.865060,83.550201,80.465863,2.931325,1013.350602,22.599747

In [ ]:
#difference between rainy and non-rainy averages
df.groupby("rainfall")["humidity"].mean().diff()
#findings: Rainy days have about 10.55% higher average humidity than non-rainy days

rainfall
no           NaN
yes    10.550201
Name: humidity, dtype: float64

In [ ]:
df.groupby("rainfall")[["maxtemp","temparature","mintemp","humidity","cloud","sunshine","pressure","windspeed"]].mean().diff()

,maxtemp,temparature,mintemp,humidity,cloud,sunshine,pressure,windspeed
rainfall,,,,,,,,
no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
yes,-1.293029,-0.450633,-0.092205,10.550201,29.209453,-4.654999,-1.226321,3.324533

In [ ]:
#Overall conclusion:
#From the dataset, a typical rainy day tends to have:
# much more cloudy(+29.20), higher humidity(+10.55), somewhat higher windspeed(3.32), slightly lower temparature, less sunshine(-4.65), slightly lower pressure(-1.22)